@echo off
echo Creating virtual environment...
python -m venv .venv

echo Activating virtual environment...
call .venv\Scripts\activate

echo Upgrading pip...
python -m pip install --upgrade pip

echo Installing dependencies...
pip install flask flask-sqlalchemy flask-login werkzeug

echo Starting Flask application...
python -m flask --app main run --debug 
